use axum::{Router, routing::post};

use crate::local_api::handlers::environments::*;
use crate::local_api::server::state::LocalApiServerState;

pub fn register_routes(router: Router<LocalApiServerState>) -> Router<LocalApiServerState> {
    router
        .route(
            "/api/local/environments/start",
            post(start_environment_handler),
        )
        .route(
            "/api/local/environments/stop",
            post(stop_environment_handler),
        )
        .route(
            "/api/local/environments/status",
            post(get_environment_status_handler),
        )
        .route(
            "/api/local/environments/cdp-endpoint",
            post(get_environment_cdp_endpoint_handler),
        )
        .route(
            "/api/local/environments/batch-start",
            post(batch_start_environments_local_handler),
        )
        .route(
            "/api/local/environments/batch-stop",
            post(batch_stop_environments_local_handler),
        )
        .route(
            "/api/local/environments/list",
            post(list_environments_handler),
        )
        .route(
            "/api/local/environments/detail",
            post(get_environment_handler),
        )
        .route(
            "/api/local/environments/batch-detail",
            post(batch_get_environments_handler),
        )
        // .route("/api/local/environments/create", post(create_environment_handler))
        // .route("/api/local/environments/batch-create", post(batch_create_environments_handler))
        // .route("/api/local/environments/update", post(update_environment_handler))
        .route(
            "/api/local/environments/delete",
            post(delete_environment_handler),
        )
        .route(
            "/api/local/environments/batch-delete",
            post(batch_delete_environments_handler),
        )
        .route(
            "/api/local/environments/set-proxy",
            post(set_environment_proxy_handler),
        )
        .route(
            "/api/local/environments/assign-tags",
            post(assign_tags_handler),
        )
        .route(
            "/api/local/environments/remove-tag",
            post(remove_tag_handler),
        )
        .route(
            "/api/local/environments/move-to-group",
            post(move_to_group_handler),
        )
        .route(
            "/api/local/environments/batch-move-to-group",
            post(batch_move_to_group_handler),
        )
        .route(
            "/api/local/environments/set-accounts",
            post(set_environment_accounts_handler),
        )
        .route(
            "/api/local/environments/batch-assign-tags",
            post(batch_assign_tags_handler),
        )
        .route(
            "/api/local/environments/batch-remove-tags",
            post(batch_remove_tags_handler),
        )
        .route(
            "/api/local/environments/urls/list",
            post(list_environment_urls_handler),
        )
        .route(
            "/api/local/environments/urls/add",
            post(add_environment_url_handler),
        )
        .route(
            "/api/local/environments/urls/delete",
            post(delete_environment_url_handler),
        )
        .route(
            "/api/local/environments/urls/clear",
            post(clear_environment_urls_handler),
        )
        .route(
            "/api/local/environments/cookies/list",
            post(list_environment_cookies_handler),
        )
        .route(
            "/api/local/environments/cookies/add",
            post(add_environment_cookie_handler),
        )
        .route(
            "/api/local/environments/cookies/delete",
            post(delete_environment_cookie_handler),
        )
        .route(
            "/api/local/environments/cookies/clear",
            post(clear_environment_cookies_handler),
        )
        .route(
            "/api/local/environments/recycle-bin/list",
            post(list_recycle_bin_environments_handler),
        )
        .route(
            "/api/local/environments/recycle-bin/restore",
            post(restore_environment_handler),
        )
        .route(
            "/api/local/environments/recycle-bin/batch-restore",
            post(batch_restore_environments_handler),
        )
        .route(
            "/api/local/environments/recycle-bin/permanent-delete",
            post(permanent_delete_environment_handler),
        )
        .route(
            "/api/local/environments/recycle-bin/batch-permanent-delete",
            post(batch_permanent_delete_environments_handler),
        )
}
