import React, { useEffect } from 'react';
import { AppLayout } from './app/components/AppLayout';
import { pluginRegistry, pluginLoader, setPluginImportFunctions } from '@slotkitjs/core';

// Import generated plugin import mappings
// This file is generated by 'slotkit generate-imports'
import * as pluginImports from './core/plugin/loader/plugin-imports.generated';

// Initialize plugin import mappings
if (pluginImports.getPluginImport && pluginImports.getAvailablePluginIds) {
  setPluginImportFunctions({
    getPluginImport: (pluginId: string) => {
      const importFn = pluginImports.getPluginImport(pluginId);
      if (!importFn) return undefined;
      return () => Promise.resolve(importFn());
    },
    getAvailablePluginIds: pluginImports.getAvailablePluginIds,
    getAllPluginManifests: pluginImports.getAllPluginManifests,
    getPluginManifest: pluginImports.getPluginManifest,
  });
} else {
  console.warn('[WARN] Plugin import functions not found in generated file');
}

// Load all plugins
const loadPlugins = async () => {
  try {
    const plugins = await pluginLoader.loadAllPlugins();

    plugins.forEach((plugin) => {
      pluginRegistry.register(plugin);
    });

    return plugins;
  } catch (error) {
    console.error('[ERROR] Failed to load plugins:', error);
    return [];
  }
};

interface AppProps {
  /**
   * 应用模式：'main' 渲染主应用布局，'splashscreen' 渲染启动屏幕，'syncer' 渲染同步器窗口
   */
  mode?: 'main' | 'splashscreen' | 'syncer';
}

const App: React.FC<AppProps> = ({ mode = 'main' }) => {
  useEffect(() => {
    loadPlugins()
      .then(() => {
        console.log('[App] Plugins loaded for mode:', mode);
      })
      .catch((error) => {
        console.error('[ERROR] Failed to load plugins:', error);
      });
  }, [mode]);

  return (
    <div className="app">
      <AppLayout mode={mode} />
    </div>
  );
};

export default App;
